spring.application.name=demo
spring.security.oauth2.client.registration.entra-id.client-id=${AZURE_CLIENT_ID}
spring.security.oauth2.client.registration.entra-id.client-secret=${AZURE_CLIENT_SECRET}
spring.security.oauth2.client.registration.entra-id.scope=openid, profile, email
spring.security.oauth2.client.registration.entra-id.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.entra-id.issuer-uri=https://login.microsoftonline.com/21696173-c883-4a8f-ab46-a3c6a89bdfdd/v2.0